1.try块和异常处理
throw表达式：错误检测部分使用这种表达式来说明遇到了不可处理的错误。throw引发(raise)了异常条件。
example:
if(condition)
	throw runtime_error("message");
else
	...

try块：错误处理部分使用它来处理异常。通常跟着一个或多个catch子句(catch clause)。catch子句也称为处理代码(handler)。
example:
try
{
	...
	if(condition)
		throw overflow_error("message");
}
catch(overflow_error oe)
{
	std::cout << oe.what() << std;:endl; //输出message
}

其中runtime_error和overflow_error均是标准库异常类，包含在<stdexcept>中，常见的有
exception:最常见的错误
runtime_error:运行时错误，只有在运行时才能检测的错误
range_error:运行时错误，生成的记过超出有意义的值域范围
overflow_error:运行时错误，计算上溢
underflow_errorL：运行时错误，计算下溢
logic_error:逻辑错误，可在运行前检测到的问题
domain_error:逻辑错误，参数的结果值不存在
invalid_error:逻辑错误，不合适的参数
length_error:逻辑错误，试图生成一个超出该类型最大长度的对象
out_of_range:逻辑错误，使用一个超出有效范围的值。

C++标准库异常类定义在4个头文件中
(1)exception:定义了最常见的异常类，这个类只通知异常的产生，但不提供更多的信息
(2)stdexcept
(3)new：定义bad_alloc异常类型，提供因无法分配内存没而由new抛出的异常
(4)type_info:定义了bad_cast异常类型

